name: CI

on:
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --recursive --frozen-lockfile

      - name: Run tests
        run: pnpm run test:run

      - name: Run TypeScript type checking
        run: pnpm run type-check

      - name: Run ESLint and fix
        run: pnpm run lint:fix

      - name: Format with Prettier
        run: pnpm run format

      - name: Check for remaining ESLint errors
        run: pnpm run lint

      - name: Check for remaining formatting issues
        run: pnpm run format:check
